### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by davisem** [xyc0813/pysim#10]
```
python specify_ploidy.py -i ~/annotations/GRCh37-lite.fa -c config -o grch37-lite.chr10.fa
2018-06-01 10:01:22
simulation begins at:0.029685
^[]Traceback (most recent call last):
  File "specify_ploidy.py", line 80, in <module>
    main()
  File "specify_ploidy.py", line 74, in main
    ref_dic=ploidy(ref_dic,config_dic)
  File "specify_ploidy.py", line 20, in ploidy
    ref_dic_new[key+'-hap-'+str(n+1)]=ref_dic[key]
KeyError: '10'
```

```
#chromName	ploidy
10	2
```

**Comment by archmageirvine** [comment]
In my case I got past this block by removing extra contents on the name line in the fasta, something like ```python2.7 specify_ploidy.py -i <(sed '/>/s/ .*//' <~/ref/38/Homo_sapiens_assembly38.fasta) -c ploidy.dat -o b38sim.fa```
